import os
import shutil
import threading
from concurrent.futures import ThreadPoolExecutor

import vpk
from core import base, config, constants, fs, log, output, security, utils


def extract(vpk_to_extract_from, paths, path_to_extract_to=base.build_dir):
    if isinstance(paths, str):
        paths = [paths]

    vpk_lock = threading.Lock()

    def extract_file(path):
        clean_path, full_path = security.confined_destination(path_to_extract_to, path)
        if not os.path.exists(full_path):  # extract files from VPK only once
            output.add_text("&extracting_terminal", clean_path)
            with vpk_lock:
                pakfile = vpk_to_extract_from.get_file(path)

            if pakfile:
                fs.create_dirs(os.path.dirname(full_path))
                pakfile.save(full_path)
            else:
                log.write_warning(f"File not found in VPK: {path}")

    with ThreadPoolExecutor() as executor:
        list(executor.map(extract_file, paths))


def dump(vpk_obj, output_dir, check_exists=True, exclude_paths=None):
    excluded = {security.safe_relative_path(str(path)).casefold() for path in (exclude_paths or [])}
    for filepath in vpk_obj:
        clean_path, full_path = security.confined_destination(output_dir, filepath)
        if clean_path.casefold() in excluded:
            continue
        if check_exists and os.path.exists(full_path):
            continue

        fs.create_dirs(os.path.dirname(full_path))
        vpk_obj.get_file(filepath).save(full_path)


def is_minify_pak(vpk_path):
    """
    Determines whether a VPK file was generated by Minify by checking for the
    metadata marker files that dump_metadata() packs into created Paks.
    """
    marker_files = ["minify_mods.json", "minify_vpk_mods.txt", "minify_version.txt"]
    marker_files += [f"{mod}.txt" for mod in constants.visually_available_mods]

    try:
        pak = vpk.open(vpk_path)
        pak_files = set(pak)
    except Exception:
        return False
    return not pak_files.isdisjoint(marker_files)


def dump_metadata(target_dir, mod_name=None, vpk_mods=None, extra_lists=None):
    """
    Standardizes metadata files for generated Paks.
    - target_dir: Where to dump.
    - mod_name: If provided, creates {mod_name}.txt (for single mod patches).
    - vpk_mods: List of VPK mod names for minify_vpk_mods.txt.
    - extra_lists: Dict of {filename: [lines]} for additional metadata files.
    """
    if config.get("opt_out_vpk_metadata", False):
        return

    # 1. Base Info
    if mod_name is None:
        shutil.copy(base.mods_config_dir, os.path.join(target_dir, "minify_mods.json"))
    else:
        open(os.path.join(target_dir, f"{mod_name}.txt"), "w").close()

    # 2. Lists
    if vpk_mods:
        with utils.open_utf8(os.path.join(target_dir, "minify_vpk_mods.txt"), "w") as f:
            f.write("\n".join(vpk_mods))

    if extra_lists:
        for filename, lines in extra_lists.items():
            with utils.open_utf8(os.path.join(target_dir, filename), "w") as f:
                f.write("\n".join(lines))

    # 3. Minify Version
    with utils.open_utf8(os.path.join(target_dir, "minify_version.txt"), "w") as f:
        f.write(base.VERSION)

    # 4. Dota Version (steam.inf)
    if os.path.exists(constants.dota_steam_inf_path):
        shutil.copy(constants.dota_steam_inf_path, os.path.join(target_dir, "steam.inf"))
